FROM tomcat:8.5.34

COPY apivigiaorquestador/apivigiaorquestadorWeb/target/vigia.war /usr/local/tomcat/webapps/vigia.war
COPY apivigiaorquestador/cloud/docker/server.xml /usr/local/tomcat/conf/
COPY apivigiaorquestador/cloud/docker/context.xml /usr/local/tomcat/conf/

EXPOSE 8080
