apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config-apivigiafrontal
data:
  fluent.conf: |
    <source>
      @type tail
      tag apivigiafrontal
      path /var/log/apivigiafrontal/apivigiafrontal.log
      exclude_path ["/var/log/apivigiafrontal/apivigiafrontal.log.*"]
      pos_file /var/log/apivigiafrontal/apivigiafrontal.log.pos
      <parse>
        @type json
      </parse>
    </source>
    <match **>
      @type elasticsearch
      host elasticsearch
      port 9200
      flush_interval 1s
      index_name "apivigiafrontal"
    </match>
    
    <label @FLUENT_LOG>
      <match fluent.*>
        @type stdout
      </match>
    </label>
