apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: apivigia-inventari
  name: apivigia-inventari
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: apivigia-inventari
  template:
    metadata:
      labels:
        k8s-app: apivigia-inventari
    spec:
      containers:
      - image: de.icr.io/vigia/apivigiainventari:1.0.0
        name: apivigia-inventari
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /services/vigia/inventari/monitor/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        env:
          - name: rest.client.apiConnect.auth.interceptor.clientId
            valueFrom:
              configMapKeyRef:
                name: credentials-imi-config
                key: CLIENT_ID
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      
---
apiVersion: v1
kind: Service
metadata:
  name: apivigia-inventari
  labels:
    k8s-app: apivigia-inventari
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    k8s-app: apivigia-inventari
  type: NodePort
  