FROM tomcat:8.5.42

COPY cloud/bluemix/vigia.war /usr/local/tomcat/webapps/vigia.war
COPY cloud/bluemix/server.xml /usr/local/tomcat/conf/
COPY cloud/bluemix/context.xml /usr/local/tomcat/conf/

EXPOSE 8080
