---
swagger: "2.0"
info:
  description: "API REST Application for state query"
  version: "1.0.0"
  title: "API.APPLICATION.STATE"
  termsOfService: "Terms of service of IMI"
  contact:
    name: "IMI"
    url: "https://www.IMI.com"
    email: "IMI@gmail.com"
  license:
    name: "IMI License"
    url: "https://www.IMI.com/License"
basePath: "/vigia/inventari"
tags:
- name: "monitor-controller"
  description: "Monitor Controller"
paths:
  /monitor/liveness:
    get:
      tags:
      - "Liveness"
      summary: "Returns monitor OK"
      operationId: "livenessUsingGET"
      produces:
      - "*/*"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/ResponseEntity«string»"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
      deprecated: false
  /monitor/uptime:
    get:
      tags:
      - "uptime"
      summary: "Returns time up server(+ip)"
      operationId: "uptimeUsingGET"
      produces:
      - "*/*"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/ResponseEntity«string»"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
      deprecated: false
definitions:
  ResponseEntity«string»:
    type: "object"
    properties:
      body:
        type: "string"
      statusCode:
        type: "string"
        enum:
        - "100"
        - "101"
        - "102"
        - "103"
        - "200"
        - "201"
        - "202"
        - "203"
        - "204"
        - "205"
        - "206"
        - "207"
        - "208"
        - "226"
        - "300"
        - "301"
        - "302"
        - "303"
        - "304"
        - "305"
        - "307"
        - "308"
        - "400"
        - "401"
        - "402"
        - "403"
        - "404"
        - "405"
        - "406"
        - "407"
        - "408"
        - "409"
        - "410"
        - "411"
        - "412"
        - "413"
        - "414"
        - "415"
        - "416"
        - "417"
        - "418"
        - "419"
        - "420"
        - "421"
        - "422"
        - "423"
        - "424"
        - "426"
        - "428"
        - "429"
        - "431"
        - "451"
        - "500"
        - "501"
        - "502"
        - "503"
        - "504"
        - "505"
        - "506"
        - "507"
        - "508"
        - "509"
        - "510"
        - "511"
      statusCodeValue:
        type: "integer"
        format: "int32"
    title: "ResponseEntity«string»"
